### ISSUE TITLE
Support for TRC20 Tokens

### ISSUE THREAD

**Issue by damascene** [ELHARAKA/TrxAutoSweep#1]
I wonder if it's possible to sweep TRC20 token from a wallet in two cases:

- Wallet with TRC20 and TRX balance
- Wallet with TRC20 tokens but no TRX balance

Is it possible to support both in your script?

**Comment by ELHARAKA** [comment]
I can help you implement this feature in my script for a fee. If you're interested, let's discuss the details and pricing.

### Here's how the modified script functionality will work:

### **Case 1:** Wallet with TRC20 and TRX balance

1. Check the balance of TRC20 tokens in the wallet using TronWeb.
2. Check the TRX balance in the wallet.
3. Ensure that the TRX balance is greater than or equal to 10 TRX to cover transaction fees.
4. If there are TRC20 tokens available, transfer them to the destination wallet.

### **Case 2:** Wallet with TRC20 tokens but no TRX balance

1. Check the balance of TRC20 tokens in the wallet using TronWeb.
2. Check the TRX balance in the wallet.
3. If there are TRC20 tokens available and the TRX balance is less than 10 TRX:
4. Automatically send 10 TRX to the wallet to cover transaction fees.
5. Transfer the entire TRC20 token balance to the destination wallet.
